resources:
  repositories:
  - repository: inlinerepo
    endpoint: ashokdsr
    name: ashokdsr/inlinerepo
    type: git

trigger:
  - main
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: windows-latest
  steps:
  - checkout: inlinerepo

  - task: PowerShell@2
    displayName: PowerShell Script
    inputs:
      targetType: 'inline'
      script: |
        $file = "inline.ps"
        #Get-Content  "$file" -Raw
        #(Get-Content $file).length
         $i = 12
        for($i=1 ; $i -le 12; $i++)
        {
         
         
        #Write-Host ($i)
         
        $i=$i+2
         
         
        $q = Get-Content $file | Select -Index ($i - 1 )
         
         
        Write-Output ($q)
         
        
        }